services:
  app:
    image: node:23-alpine
    depends_on:
      - postgres
    command: sh -c "npm install &&
                    npx sequelize-cli db:migrate &&
                    npx sequelize-cli db:seed:all &&
                    npm start"
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      DB_HOST: postgres
      DB_NAME: charapi
      DB_USERNAME: postgres
      DB_PASSWORD: root

  postgres:
    image: postgres:17.2
    volumes:
      - charapi-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: charapi
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
volumes:
  charapi-data: